### ISSUE TITLE
Diagnostic Checklist

### ISSUE THREAD

**Issue by nwillems94** [nwillems94/dgen#2]
Some basic checks for code verification

- [x] Residential & Commercial Sectors

### Geographies
- [X] Single state

- [X] Other states

- [x] Set of states (PJM or one of the ISO's)

- [ ] National

### Edge cases
- [ ] Robustness within reasonable set of parameters 

- [ ] Free solar

- [ ] Universal feed-in tariff

### Code characteristics 
- [ ] Changing datatypes around code blocks

- [ ] Effect on runtime
